"""create tables

Revision ID: 424c4f3790bd
Revises: c7f9ddfe9c23
Create Date: 2022-08-22 11:20:18.614294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424c4f3790bd'
down_revision = 'c7f9ddfe9c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_order_timestamp'), 'user_order', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_order_timestamp'), table_name='user_order')
    op.drop_table('user_order')
    # ### end Alembic commands ###
